### ISSUE TITLE
[FR]: Heat Supply Request Sensor

### ISSUE THREAD

**Issue by DKwinther** [MTrab/danfoss_ally#35]
In the documentation it seems like it should be possible to get a Heat Supply Request signal from the thermostats.
Having the "Heat Supply Request" signal as a sensor, could be really cool as it would be easier to plot when the thermostat is actually heating and not.

I have already made a binary sensor that compare the target with the current temperature but its not fully correct as there seems to be a preheating sequence in the Ally software. Therefore the request. 
https://assets.danfoss.com/documents/193613/AM375549618098en-000102.pdf

Awesome integration btw!

**Comment by jnxxx** [comment]
The issue we have, is that we are missing some documentation from Danfoss regarding the purpose of each of the attributes exposed in the API. For some of them the name makes it obvious, for others not so much.

For radiators we do get a `heat_supply_request`, but not for floor heating.
Do you know what it indicates? Is it a signal to a gas boiler?
And how does it differ from `heat_available` and `boiler_relay`?

For both radiators and floor heating we already have an indication of when it is heating and not.
This is read from the `work_state` attribute.
In HA you will see it as `hvac_action` on the climate entity with values heating or idle.

It is also plotted automatically in the history graph as the orange bars:
![image](https://user-images.githubusercontent.com/20459196/214384610-3b6c4e08-4d70-4627-b0c2-d2569ef9ceb8.png)

**Comment by rijk82** [comment]
I am also looking for a way to see when there is active heating. @jnxxx mentioned the hvac_action property in HA and the auto plotting of this on the history graph. I see neither - am I missing something?
![image](https://github.com/MTrab/danfoss_ally/assets/19733272/4f79fea8-3268-408c-9b12-1871b1929a8a)
![image](https://github.com/MTrab/danfoss_ally/assets/19733272/1c8fc683-2592-41bd-b370-f000989a288d)

**Comment by jnxxx** [comment]
On your first image, click climate entity you have int the Controls section.
Next, in the popup window, click on the history icon at the top.

If you check states in developer tools, you will find the attribute `hvac_action` on `climate` entities:
![image](https://github.com/MTrab/danfoss_ally/assets/20459196/2ea40010-0c32-45c8-971e-248696f41ea2)


To show it in a lovelace card, you can do something like this:
```
type: history-graph
entities:
  - entity: climate.entre_bryggers
```

To show current state without history, you can do:
```
type: glance
entities:
  - entity: climate.entre_bryggers
    name: Bryggers
```

Apart from that it is not that easy to use because it is an attribute and not the state of an entity/sensor.
To make it a separate sensor you can use a [template sensor](https://www.home-assistant.io/integrations/template/).

One issue I noticed though is that Ally seems to have an issue reporting hvac_action reliably. For long periods it happens that it reports off or on constantly. When that happens, I find that power cycling the Ally gateway solves the issue.

**Comment by MTrab** [comment]
If I'm not wrong, this issue is actually fixed, right?

**Comment by jnxxx** [comment]
I think so.
For radiators we have `heat supply request` as a separate sensor.

And for both radiators and floor heating (Icon) we have `hvac_action` on the climate control.
However, sometimes it is somewhat cumbersome to use as an attribute. A slight improvement could be to _also_ make hvac_action available as a separate binary sensor. It could be off by default.
It can also be implemented using a template sensor, but would not be related to the device.

**Comment by rijk82** [comment]
I still find the hvac_action to be very temperamental, often being stuck as
either idle or heating with very little relationship to what the heating
system in the home is actually doing.
