### ISSUE TITLE
Get target temperature

### ISSUE THREAD

**Issue by oveand** [MTrab/danfoss_ally#9]
Hi,
Thank you for a nice plugin.

Is it true that the integration (and probably the Danfoss API) only and always returns "Home" temperature and not the actual target temperature?

The following trv is running a schedule and is currently in "away" state. Home temp is 22, away temp is 20.5:
`<template TemplateState(<state climate.sovevaerelse_radiator=heat; hvac_modes=['heat'], min_temp=5.0, max_temp=35.0, target_temp_step=0.5, current_temperature=20.4, temperature=22.0, hvac_action=heating, friendly_name=Soveværelse radiator, supported_features=1 @ 2022-01-06T11:10:32.634197+01:00>)>`

The following trv is currently running on a fixed manual target temp of 22 with a home temp of 22.5 and an away temp of 21:
`<template TemplateState(<state climate.kokken_radiator=heat; hvac_modes=['heat'], min_temp=5.0, max_temp=35.0, target_temp_step=0.5, current_temperature=22.4, temperature=22.5, hvac_action=heating, friendly_name=Køkken radiator, supported_features=1 @ 2022-01-06T11:10:32.631866+01:00>)>`
These were outputted from template {{states.climate.kokken_radiator}}

Is my gateway screwed up or is it the API which doesn't support showing the current target temperature?

**Comment by MTrab** [comment]
Must say, I have more or less given up on this plug-in :/
Danfoss doesn't seem to take their own product serious, as any error reporting just get binned in some large bitbucket :(

I have several times seen inconsistensy between what is reported by the API and what is the actual state on the physical devices.

That said, I'm not sure what you mean by your message - is it that whatever setting you set on the physical devices is not reflected byt the plugin (API)? or?!

**Comment by oveand** [comment]
Yeah unfortunately it seems like you're right. I have a couple of error reportings and requests with no answer from Danfoss at all. Quite disappointing. I'm using your plugin mainly for temperature logging as the app is fairly usable and easy to use.

What I meant was that I cannot get the actual setpoint temperature from any of my TRVs using the API. It always reports the "home" temperature set i the app.

But from what I hear from you I might completely skip the gateway and API and just pair them directly with ZHA. Then I can also use external sensors as it seems like these have been on the way for more than a year.

**Comment by MTrab** [comment]
I'm still not sure what you mean by home and away temperature. The API reports the current setpoint, and that's what the plugin uses.

**Comment by oveand** [comment]
In the Danfoss Ally app you set, for each room, home, away and pause temp.
For me the home temp i always reported as temperature through the API. The target temp you can see on the TRV is not reported.

![C65DC4C4-1A43-45B3-B1A3-7074AB1126FE](https://user-images.githubusercontent.com/13885942/148377359-a383e257-5567-4b72-94eb-b0e7e04e7888.png)

**Comment by MTrab** [comment]
Okay - that sounds excactly like the API/Gateway inconsistency I've seen several times.
Unfortunately this is all in Danfoss hands, I cannot help with this issue.

**Comment by oveand** [comment]
I was suspecting this, thanks anyway 😊

**Comment by jnxxx** [comment]
Don't give up... 🥺

I see the integration reads and writes `temp_set` in the API.
I too can conclude it reads the Home setpoint and seem to write the Manual setpoint.

I have not seen any documentation from Danfoss on what `temp_set` is meant to represent. Should it read/write the setpoint for the current mode? In any case it seems strange it reads and writes different setpoints.

Locally I have made a change to it, so instead it uses `manual_mode_fast`. Now it works reliably, I believe, but of course always for the manual setpoint.

Question is how you intend the climate control to work?

Should it always show and set the manual setpoint, then just change `temp_set` to `manual_mode_fast` (not tested with radiator thermostats).

Should it show and set the setpoint for the current preset mode, then probably use:
-   Manual: `manual_mode_fast`
-   Home: `at_home_setting`
-   Away: `leaving_home_setting`
-   Pause: `pause_setting`
-   Holiday: `holiday_setting`

when reading and writing, depending the the current preset mode.

The app can set these setpoints independent of the preset mode.
To allow for this, maybe implement a service call (I think it is [this](https://developers.home-assistant.io/docs/device_automation_action)).
Alternatively, implement a full climate control for each....

**Floor temperature sensor**
I also extended my local version with a floor temperature sensor, read from `MeasuredValue` if 'floor_sensor' is true.
To also be able to read and write the min and max setpoints, it should probably have its own climate control with `TARGET_TEMPERATURE_RANGE` rather than `TARGET_TEMPERATURE`.
I tried if one climate control can handle both, but it doesn't seem to work properly.

I can share what I have, but I had to place pydanfossally locally also, so not ideal to make a pull request.
